<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
# Uncomment and install the below to start CUDA is required for this file , i suggest you to run this on Google Colab

# !pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

In [2]:
#credit: Udemy

In [5]:
import torch
import numpy
import torchvision
import matplotlib.pyplot as plt

In [6]:
torch.cuda.is_available()

True

In [8]:
# This is a 1-D tensor
a= torch.tensor([0.11111, 0.222222, 0.3333333])
print(a)

tensor([0.1111, 0.2222, 0.3333])


In [11]:
# This is 2-D tensor

b=torch.tensor([[0.11111, 0.222222, 0.3333333],[0.11111, 0.222222, 0.3333333],[0.11111, 0.222222, 0.3333333],[0.11111, 0.222222, 0.3333333]])
print(b)

tensor([[0.1111, 0.2222, 0.3333],
        [0.1111, 0.2222, 0.3333],
        [0.1111, 0.2222, 0.3333],
        [0.1111, 0.2222, 0.3333]])


In [13]:
# Get the shape and size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [15]:
print(b.shape[0])  # To get the shape of the Tensor "b"

4


In [20]:
# we are trying to get the FloatTensor here.
c = torch.FloatTensor([[1, 2, 3],[1, 2, 3],[1, 2, 3],[1, 2, 3]])
print(c)
print(c.dtype)

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])
torch.float32


In [27]:
# we are trying to get the DoubleTensor here.
d = torch.DoubleTensor([[1, 2, 3],[1, 2, 3],[1, 2, 3],[1, 2, 3]])
print(d)
print(d.dtype)

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]], dtype=torch.float64)
torch.float64


In [26]:
print(c.mean())
print(c.std())

tensor(2.)
tensor(0.8528)


In [25]:
print(d.mean())
print(d.std())

tensor(2., dtype=torch.float64)
tensor(0.8528, dtype=torch.float64)


In [32]:
# Reshaping the Tensor, The method to reshape tensor is called "View"
# If one of the dimension is -1 , its size can be inferred in this case its "1" dimension ,  with -1(any) rows  and 1 coloumn (4 times sh means 12 times 1 rows)
sh =torch.tensor([[0.11111, 0.222222, 0.3333333],[0.11111, 0.222222, 0.3333333],[0.11111, 0.222222, 0.3333333],[1, 2, 3]])
print(sh.view(-1,1))

tensor([[0.1111],
        [0.2222],
        [0.3333],
        [0.1111],
        [0.2222],
        [0.3333],
        [0.1111],
        [0.2222],
        [0.3333],
        [1.0000],
        [2.0000],
        [3.0000]])


In [33]:
# Flattern the tensor. (12 times sh)
print(sh.view(12))

tensor([0.1111, 0.2222, 0.3333, 0.1111, 0.2222, 0.3333, 0.1111, 0.2222, 0.3333,
        1.0000, 2.0000, 3.0000])


In [34]:
# Any number of rows and 4 number columns
print(sh.view(-1,4))

tensor([[0.1111, 0.2222, 0.3333, 0.1111],
        [0.2222, 0.3333, 0.1111, 0.2222],
        [0.3333, 1.0000, 2.0000, 3.0000]])


In [35]:
# here it is same as the previous cell , 3 rows and 4 columns
print(sh.view(3,4))

tensor([[0.1111, 0.2222, 0.3333, 0.1111],
        [0.2222, 0.3333, 0.1111, 0.2222],
        [0.3333, 1.0000, 2.0000, 3.0000]])


In [36]:
# 1 row and any number of columns , shape is (1 , 12)
sh = sh.view(1,-1)
print(sh)
print(sh.shape)

tensor([[0.1111, 0.2222, 0.3333, 0.1111, 0.2222, 0.3333, 0.1111, 0.2222, 0.3333,
         1.0000, 2.0000, 3.0000]])
torch.Size([1, 12])


In [51]:
# Create 3D tensor with 4 channels , 3 rows and 4 columns ( channels ,  rows,  columns)
# torch.randn Returns a tensor filled with random numbers from a normal distribution with mean `0` and variance `1` 
# (also called the standard normal distribution).
seed = 100   # To have the same session of the random numbers
Dimension_3 = torch.randn(2,3,4)
print(Dimension_3)

tensor([[[ 1.6319,  0.0619,  0.5238, -0.3842],
         [-0.0763, -1.0541, -0.4336, -0.5802],
         [-0.7191, -1.7496, -0.7610,  0.0785]],

        [[-0.0924, -0.3576,  0.1285,  0.4351],
         [-0.5643, -1.0729, -0.1022, -1.2720],
         [-0.5729,  1.8820, -0.5139, -1.6357]]])


In [62]:
# Reshaping Dimension_3 Tensor to 2 rows and  12 columns (rows, columns)
print(Dimension_3.view(2,12))

tensor([[ 1.6319,  0.0619,  0.5238, -0.3842, -0.0763, -1.0541, -0.4336, -0.5802,
         -0.7191, -1.7496, -0.7610,  0.0785],
        [-0.0924, -0.3576,  0.1285,  0.4351, -0.5643, -1.0729, -0.1022, -1.2720,
         -0.5729,  1.8820, -0.5139, -1.6357]])


In [63]:
# Reshaping Dimension_3 Tensor to 2 rows and  12 columns (rows, columns)
print(Dimension_3.view(2,-1)) 

tensor([[ 1.6319,  0.0619,  0.5238, -0.3842, -0.0763, -1.0541, -0.4336, -0.5802,
         -0.7191, -1.7496, -0.7610,  0.0785],
        [-0.0924, -0.3576,  0.1285,  0.4351, -0.5643, -1.0729, -0.1022, -1.2720,
         -0.5729,  1.8820, -0.5139, -1.6357]])


In [64]:
# Reshaping Dimension_3 Tensor to 1 rows and "n" number columns
print(Dimension_3.view(1,-1))

tensor([[ 1.6319,  0.0619,  0.5238, -0.3842, -0.0763, -1.0541, -0.4336, -0.5802,
         -0.7191, -1.7496, -0.7610,  0.0785, -0.0924, -0.3576,  0.1285,  0.4351,
         -0.5643, -1.0729, -0.1022, -1.2720, -0.5729,  1.8820, -0.5139, -1.6357]])


In [111]:
# torch.rand Returns a tensor filled with random numbers from a uniform distribution on the interval :math:`[0, 1)` 
sha = torch.rand(4,4)
print(sha)
print(sha.dtype)

tensor([[0.4916, 0.7155, 0.6845, 0.8136],
        [0.1889, 0.4421, 0.5905, 0.0568],
        [0.1973, 0.8802, 0.5052, 0.6741],
        [0.2096, 0.1187, 0.1240, 0.0101]])
torch.float32


In [102]:
# Create anarray of 5 random intigers from value between 2 and 7 and (exclusive of 8 )
# torch.randint Returns a tensor filled with random integers generated uniformly between :attr:`low` (inclusive) and :attr:`high` (exclusive).
sh1 = torch.randint(2,8 , (10,))   # Intiger between 2-8 and tensor of shape (10,0)
print(sh1)
print(sh1.dtype)

tensor([6, 6, 5, 4, 2, 4, 7, 3, 5, 7])
torch.int64


In [103]:
# for 2-D array
sh2 = torch.randint(2,8 , (5,5))   # Intiger between 2-8 and tensor of shape (5,5)
print(sh2)
print(sh2.dtype)

tensor([[7, 2, 2, 7, 3],
        [5, 7, 3, 7, 2],
        [2, 2, 7, 7, 5],
        [2, 6, 6, 3, 7],
        [2, 6, 2, 6, 5]])
torch.int64


In [104]:
# Get the number of elements in array 
# torch.numel : Returns the total number of elements in the :attr:`input` tensor.
print(torch.numel(sh1))
print(sh1.dtype)
print(torch.numel(sh2))
print(sh2.dtype)

10
torch.int64
25
torch.int64


In [106]:
# Construct 3X3 matrix of zeros and of type long
# Returns a tensor filled with the scalar value `0`, with the shape defined by the variable argument :attr:`size`.

sh3 = torch.zeros(3,3 , dtype=torch.long)
print(sh3)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [110]:
# Construct 3X3 matrix of zeros and of type long
# torch.ones : Returns a tensor filled with the scalar value `1`, with the shape defined by the variable argument :attr:`size`.
sh6 = torch.ones(3,3 , dtype=torch.long)
print(sh6)
print(sh6.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
torch.int64


In [113]:
# Convert the datatype of Tensor
# Returns a tensor with the same size as :attr:`input` that is filled with
# random numbers from a uniform distribution on the interval :math:`[0, 1)`.
# ``torch.rand_like(input)`` is equivalent to
# ``torch.rand(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.

data_like = torch.rand_like(sha , dtype=torch.double)
print(data_like)
print(data_like.dtype)

tensor([[0.4551, 0.6606, 0.5147, 0.9909],
        [0.5258, 0.5868, 0.6577, 0.2414],
        [0.6323, 0.7684, 0.4844, 0.1206],
        [0.2160, 0.5144, 0.3097, 0.9785]], dtype=torch.float64)
torch.float64


In [114]:
# Adding 2 tensors, which should have same size and same data type
# torch.add : Adds the scalar :attr:`other` to each element of the input :attr:`input` and returns a new resulting tensor.
Add_result = torch.add(data_like , sha)
print(Add_result)

tensor([[0.9467, 1.3762, 1.1992, 1.8045],
        [0.7146, 1.0289, 1.2482, 0.2981],
        [0.8296, 1.6486, 0.9895, 0.7947],
        [0.4256, 0.6330, 0.4337, 0.9886]], dtype=torch.float64)


In [115]:
# In-place addition (changing the value of sha)
sha.add_(data_like)
print(sha)

tensor([[0.9467, 1.3762, 1.1992, 1.8045],
        [0.7146, 1.0289, 1.2482, 0.2981],
        [0.8296, 1.6486, 0.9895, 0.7947],
        [0.4256, 0.6330, 0.4337, 0.9886]])


In [122]:
# Other Operations Matrix slicing
seed = 200
print(sha)
print("*"*50)
print(sha[:,1])  # All the rows in the 1st column
print("*"*50)
print(sha[:,:2])  # All the rows and upto 2 columns
print("*"*50)
print(sha[:3,:])  # Upto 3 rows and all columns
print("*"*50)
other = sha[2,3]  
print(other)       # Extracting single number 2nd row and 3rd column ( remember index starts from "0")
print("*"*50)
print(other.item())  # Extract the number from tensor ".item()"
print("*"*50 )
print(sha[2,:])  # 2nd row all columns

tensor([[0.9467, 1.3762, 1.1992, 1.8045],
        [0.7146, 1.0289, 1.2482, 0.2981],
        [0.8296, 1.6486, 0.9895, 0.7947],
        [0.4256, 0.6330, 0.4337, 0.9886]])
**************************************************
tensor([1.3762, 1.0289, 1.6486, 0.6330])
**************************************************
tensor([[0.9467, 1.3762],
        [0.7146, 1.0289],
        [0.8296, 1.6486],
        [0.4256, 0.6330]])
**************************************************
tensor([[0.9467, 1.3762, 1.1992, 1.8045],
        [0.7146, 1.0289, 1.2482, 0.2981],
        [0.8296, 1.6486, 0.9895, 0.7947]])
**************************************************
tensor(0.7947)
**************************************************
0.7946618795394897
**************************************************
tensor([0.8296, 1.6486, 0.9895, 0.7947])


**Numpy Bridge**

In [123]:
import numpy as np

In [138]:
one_torch = torch.ones(4)
print(one_torch , ",",one_torch.dtype)

tensor([1., 1., 1., 1.]) , torch.float32


In [139]:
# Converting torch to numpy array
one_numpy = one_torch.numpy()
print(one_numpy , " , ",one_numpy.dtype)

[1. 1. 1. 1.]  ,  float32


In [140]:
# Changing one_numpy array by changing one_torch by In-place operation ( this is called numpy bridge , whatever happens to numpy also happens to torch )
one_torch.add_(2)
print(one_numpy ," , ", one_torch)

[3. 3. 3. 3.]  ,  tensor([3., 3., 3., 3.])


In [142]:
# Converting numpy array to torch tensor 

two_numpy = numpy.ones(3)
print(two_numpy , ",", two_numpy.dtype)

[1. 1. 1.] , float64


In [143]:
# from_numpy(ndarray) -> Tensor : Creates a :class:`Tensor` from a :class:`numpy.ndarray`.
two_torch = torch.from_numpy(two_numpy)
print(two_torch , ",", two_torch.dtype)

tensor([1., 1., 1.], dtype=torch.float64) , torch.float64


In [144]:
# Changing two_torch array by changing two_numpy by In-place operation ( this is called numpy bridge)

np.add(two_numpy, 2 , out=two_numpy)
print(two_numpy , "," , two_torch)

[3. 3. 3.] , tensor([3., 3., 3.], dtype=torch.float64)


In [145]:
# Move Tensor to the GPU
sha = sha.cuda()
print(sha)

tensor([[0.9467, 1.3762, 1.1992, 1.8045],
        [0.7146, 1.0289, 1.2482, 0.2981],
        [0.8296, 1.6486, 0.9895, 0.7947],
        [0.4256, 0.6330, 0.4337, 0.9886]], device='cuda:0')


In [147]:
# provide easy switching between CPU and GPU

CUDA = torch.cuda.is_available()
print(CUDA)
if CUDA:
  Add_result = Add_result.cuda()
  print(Add_result)

True
tensor([[0.9467, 1.3762, 1.1992, 1.8045],
        [0.7146, 1.0289, 1.2482, 0.2981],
        [0.8296, 1.6486, 0.9895, 0.7947],
        [0.4256, 0.6330, 0.4337, 0.9886]], device='cuda:0',
       dtype=torch.float64)


In [148]:
# Converting List to Tensor

lis = [1,2,3,4,5]
print(lis)
lis_torch = torch.tensor(lis)
print(lis ,",",lis_torch)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5] , tensor([1, 2, 3, 4, 5])


In [151]:
lis1 = [0.9467, 1.3762, 
        1.1992, 1.8045]

lis1_torch = torch.tensor(lis1)
print(lis1 , " , " ,lis1_torch , ",", lis1_torch.dtype )

[0.9467, 1.3762, 1.1992, 1.8045]  ,  tensor([0.9467, 1.3762, 1.1992, 1.8045]) , torch.float32


**Tensor Concatenation**

In [163]:
# Tensor Concatinate

tensor_1 = torch.randn(2,4)
tensor_2 = torch.randn(3,4)
print(tensor_1 , "\n\n", tensor_2)

# Concate along 0 dimensiion (concatination rows)
# torch.cat : Concatenates the given sequence of :attr:`seq` tensors in the given dimension.
# All tensors must either have the same shape (except in the concatenating
# dimension) or be empty.

concat =  torch.cat([tensor_1 , tensor_2])
print("\n", concat ,"\n")

print("*"*50 , "\n")

# Concate along 1 dimensiion (concatination Columns)

tensor_3 = torch.randn(2,4)
tensor_4 = torch.randn(2,3)
print(tensor_3 , "\n\n", tensor_4)

concat1 =  torch.cat([tensor_3 , tensor_4] , 1)
print("\n", concat1)


tensor([[-0.7518, -0.0626, -0.0173,  1.0446],
        [ 0.0695,  0.5356, -0.4749,  0.7661]]) 

 tensor([[ 1.5182,  1.2758, -0.2990, -0.5330],
        [-0.2530,  1.2537,  0.4871, -0.3752],
        [-1.5918, -0.9506, -0.3039, -0.2444]])

 tensor([[-0.7518, -0.0626, -0.0173,  1.0446],
        [ 0.0695,  0.5356, -0.4749,  0.7661],
        [ 1.5182,  1.2758, -0.2990, -0.5330],
        [-0.2530,  1.2537,  0.4871, -0.3752],
        [-1.5918, -0.9506, -0.3039, -0.2444]]) 

************************************************** 

tensor([[ 0.9934,  0.9257,  0.5404,  0.4575],
        [-0.1119,  0.5105,  1.0251, -0.6599]]) 

 tensor([[ 0.7549,  1.0703, -0.3227],
        [ 0.7037,  0.2800, -0.1387]])

 tensor([[ 0.9934,  0.9257,  0.5404,  0.4575,  0.7549,  1.0703, -0.3227],
        [-0.1119,  0.5105,  1.0251, -0.6599,  0.7037,  0.2800, -0.1387]])


**Adding Dimensions to tensors**

In [169]:
# 2-D tensor 
tensor_base = torch.tensor([1,2,3,4])
tensor_b = torch.unsqueeze(tensor_base, 0)
print(tensor_b , ',', tensor_b.shape , '\n')

tensor_c = torch.unsqueeze(tensor_base, 1)
print(tensor_c , ",", tensor_c.shape)


tensor([[1, 2, 3, 4]]) , torch.Size([1, 4]) 

tensor([[1],
        [2],
        [3],
        [4]]) , torch.Size([4, 1])


In [185]:
# 3-D tensor

tensor_3D_base = torch.rand(2,3,4)
print(tensor_3D_base , ",", tensor_3D_base.shape, "\n")

# extract tensor
tensor_3D1 = tensor_3D_base[:,:,2]
print(tensor_3D1 ,"," , tensor_3D1.shape, '\n')

# Add additional dimension
tensor_3D2= torch.unsqueeze(tensor_3D_base,2)
print(tensor_3D2 ,"," , tensor_3D2.shape, '\n')

tensor_3D3= torch.unsqueeze(tensor_3D1,2)
print(tensor_3D3 ,"," , tensor_3D3.shape, '\n')


tensor_3D2= torch.unsqueeze(tensor_3D_base,1)
print(tensor_3D2 ,"," , tensor_3D2.shape, '\n')

tensor_3D3= torch.unsqueeze(tensor_3D1,1)
print(tensor_3D3 ,"," , tensor_3D3.shape, '\n')

tensor([[[0.0808, 0.9506, 0.5715, 0.0052],
         [0.6377, 0.4387, 0.4348, 0.1285],
         [0.5354, 0.7776, 0.0280, 0.9350]],

        [[0.4342, 0.5942, 0.3788, 0.5246],
         [0.1459, 0.2398, 0.6579, 0.4705],
         [0.8525, 0.7015, 0.8523, 0.5445]]]) , torch.Size([2, 3, 4]) 

tensor([[0.5715, 0.4348, 0.0280],
        [0.3788, 0.6579, 0.8523]]) , torch.Size([2, 3]) 

tensor([[[[0.0808, 0.9506, 0.5715, 0.0052]],

         [[0.6377, 0.4387, 0.4348, 0.1285]],

         [[0.5354, 0.7776, 0.0280, 0.9350]]],


        [[[0.4342, 0.5942, 0.3788, 0.5246]],

         [[0.1459, 0.2398, 0.6579, 0.4705]],

         [[0.8525, 0.7015, 0.8523, 0.5445]]]]) , torch.Size([2, 3, 1, 4]) 

tensor([[[0.5715],
         [0.4348],
         [0.0280]],

        [[0.3788],
         [0.6579],
         [0.8523]]]) , torch.Size([2, 3, 1]) 

tensor([[[[0.0808, 0.9506, 0.5715, 0.0052],
          [0.6377, 0.4387, 0.4348, 0.1285],
          [0.5354, 0.7776, 0.0280, 0.9350]]],


        [[[0.4342, 0.5942, 0.378

**AutoGrad**